# -*- coding: utf-8 -*-
"""Heath care patient analysis system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fzTexPOfRTN8opchkyx8Llt1OFjQtY_N

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Generate Synthetic Dataset"""

np.random.seed(42)

n = 10000

data = {
    "Patient_ID": range(1, n+1),
    "Age": np.random.randint(20, 81, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Blood_Pressure": np.random.randint(80, 181, n),
    "Sugar_Level": np.random.randint(70, 201, n),
    "Cholesterol": np.random.randint(150, 301, n),
    "Heart_Rate": np.random.randint(60, 121, n)
}

df = pd.DataFrame(data)

df.to_csv("healthcare_data.csv", index=False)

print("Dataset Created Successfully!")
print(df.head())

"""Data Cleaning"""

print("\nMissing Values:\n", df.isnull().sum())

"""Descriptive Statistics"""

print("\nStatistical Summary:\n", df.describe())

"""Risk Classification"""

def classify_risk(row):
    if (row["Blood_Pressure"] > 140 or
        row["Sugar_Level"] > 160 or
        row["Cholesterol"] > 240 or
        row["Heart_Rate"] > 100):
        return "High"
    elif (row["Blood_Pressure"] > 120 or
          row["Sugar_Level"] > 140):
        return "Medium"
    else:
        return "Low"

df["Risk_Level"] = df.apply(classify_risk, axis=1)

df.head()

"""Group Analysis"""

print("\nAge vs Blood Pressure:\n", df.groupby("Age")["Blood_Pressure"].mean())

print("\nGender-wise Analysis:\n", df.groupby("Gender")
[["Blood_Pressure","Sugar_Level","Cholesterol"]].mean())

"""Visualization

Histogram
"""



df["Age"].hist()
plt.title("Age Distribution")
plt.show()

"""Bar Chart"""

df["Risk_Level"].value_counts().plot(kind='bar')
plt.title("Risk Level Distribution")
plt.show()

"""Scatter Plot"""

plt.scatter(df["Age"], df["Blood_Pressure"])
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.title("Age vs Blood Pressure")
plt.show()

"""Box Plot"""

sns.boxplot(x=df["Cholesterol"])
plt.title("Cholesterol Distribution")
plt.show()

"""Heatmap"""

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""High Risk Patients"""

high_risk = df[df["Risk_Level"] == "High"]

print("\nHigh Risk Patients Count:", len(high_risk))
print(high_risk.head())